name: "Books Tracker"

description: "Track your reading using GitHub Actions"

author: "Anand Chowdhary <https://github.com/AnandChowdhary>"

inputs:
  command:
    required: true
    description: "Command to run"

runs:
  using: "node16"
  main: "dist/index.js"

branding:
  icon: "book-open"
  color: "purple"
